version: '3'
services:
  jenkins:
    build: .
    image: rakutenbic/jenkins:lts
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - /home/ubuntu/springboot-jenkins-docker-demo/jenkins_home:/var/jenkins_home
    container_name: ci-jenkins

